name = "MyExample"
uuid = "79bf5f8a-73d8-4831-9261-5229fa183960"
authors = ["Abhishek Bhatt"]
version = "0.1.0"

[compat]
julia = "1.6.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
